// web-server.cjs (CommonJS) — elmas-web
// Purpose: Open a video ad inside Telegram, show countdown overlay, and (optionally) auto-credit reward
// Requirements (ENV on elmas-web service):
//   SUPABASE_URL
//   SUPABASE_SERVICE_ROLE_KEY
//
// Expected tables/columns (Supabase):
//   ads: id, title, url, seconds, reward, is_active
//   users: tg_id (text/bigint), balance_tl (numeric), token (numeric)
//   ad_watch_sessions: id (uuid), tg_id (text), ad_id (bigint), required_seconds (int),
//                     started_at (timestamptz), completed_at (timestamptz), paid (bool)

const express = require("express");
const { createClient } = require("@supabase/supabase-js");

const app = express();
app.use(express.json());

const PORT = process.env.PORT || 10000;

const SUPABASE_URL = process.env.SUPABASE_URL;
const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
  console.error("❌ Missing SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY in ENV");
}

const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
  auth: { persistSession: false },
});

app.get("/", (req, res) => res.status(200).send("elmas-web OK"));
app.get("/health", (req, res) =>
  res.status(200).json({ ok: true, service: "elmas-web", ts: Date.now() })
);

/**
 * Renders the ad page.
 * Link format (generated by bot): https://elmas-web.onrender.com/ad/<sessionId>
 */
app.get("/ad/:sessionId", async (req, res) => {
  try {
    const { sessionId } = req.params;

    const { data: session, error: sErr } = await supabase
      .from("ad_watch_sessions")
      .select("id,tg_id,ad_id,required_seconds,started_at,paid")
      .eq("id", sessionId)
      .maybeSingle();

    if (sErr || !session) return res.status(404).send("Session not found.");

    const { data: ad, error: aErr } = await supabase
      .from("ads")
      .select("id,title,url,seconds,reward,is_active")
      .eq("id", session.ad_id)
      .maybeSingle();

    if (aErr || !ad) return res.status(404).send("Ad not found.");
    if (ad.is_active !== true) return res.status(404).send("Ad not active.");

    const seconds = Math.max(
      10,
      Number(session.required_seconds || ad.seconds || 10)
    );
    const reward = Math.max(0, Number(ad.reward || 0));
    const title = ad.title || "Reklam";
    const videoUrl = ad.url || "";

    // If ads.url is a YouTube link, it won't autoplay reliably inside Telegram.
    // Best: use a direct mp4 URL.
    res.setHeader("Content-Type", "text/html; charset=utf-8");
    res.send(`
<!doctype html>
<html lang="tr">
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover"/>
  <title>${escapeHtml(title)}</title>
  <style>
    :root { color-scheme: dark; }
    body{margin:0;background:#0b1220;color:#fff;font-family:Arial,system-ui,-apple-system}
    .wrap{max-width:720px;margin:0 auto;padding:14px}
    .card{background:#121a2b;border-radius:16px;padding:14px;box-shadow:0 8px 30px rgba(0,0,0,.35)}
    .row{display:flex;justify-content:space-between;align-items:center;gap:12px;flex-wrap:wrap}
    .pill{background:#1b2740;border-radius:999px;padding:8px 12px;font-weight:700}
    .muted{opacity:.8;font-size:13px}
    .videoBox{position:relative;margin-top:12px;border-radius:14px;overflow:hidden;background:#000}
    video, iframe{display:block;width:100%;height:min(72vh,520px);background:#000}
    .overlay{
      position:absolute;left:10px;top:10px;z-index:5;
      background:rgba(0,0,0,.65);backdrop-filter: blur(6px);
      border-radius:12px;padding:10px 12px;font-weight:800
    }
    .btn{
      display:inline-block;margin-top:12px;
      background:#2d6cdf;border-radius:12px;padding:12px 14px;color:#fff;text-decoration:none;
      font-weight:800
    }
    .btn[disabled]{opacity:.5;pointer-events:none}
    .ok{margin-top:10px;color:#8ff0a4;font-weight:800;display:none}
    .bad{margin-top:10px;color:#ff9aa2;font-weight:800;display:none}
  </style>
</head>
<body>
  <div class="wrap">
    <div class="card">
      <div class="row">
        <div>
          <div style="font-size:18px;font-weight:900">${escapeHtml(title)}</div>
          <div class="muted">Süre dolmadan ödül verilmez. Sayfayı kapatma.</div>
        </div>
        <div class="pill">Ödül: ${reward.toFixed(2)} TL + ${reward.toFixed(2)} ELMAS</div>
      </div>

      <div class="videoBox">
        <div class="overlay">Kalan: <span id="t">--</span> sn</div>
        ${
          videoUrl
            ? `<video id="v" src="${escapeAttr(videoUrl)}" controls playsinline autoplay></video>`
            : `<div style="padding:18px">❌ Bu reklam için video URL yok. (ads.url boş)</div>`
        }
      </div>

      <div id="ok" class="ok">✅ Süre doldu. Ödül gönderiliyor...</div>
      <div id="bad" class="bad">❌ Ödül verilemedi. Daha sonra tekrar dene.</div>

      <div class="muted" style="margin-top:10px">
        Eğer video açılmıyorsa: ads.url alanına direkt <b>.mp4</b> linki koy.
      </div>
    </div>
  </div>

<script>
  const REQUIRED = ${seconds};
  const SESSION_ID = ${JSON.stringify(sessionId)};
  const tEl = document.getElementById("t");
  const okEl = document.getElementById("ok");
  const badEl = document.getElementById("bad");
  const vid = document.getElementById("v");

  let left = REQUIRED;
  let timer = null;
  let completed = false;

  function tick(){
    tEl.textContent = left;
    left -= 1;
    if(left < 0){
      finish();
      return;
    }
    timer = setTimeout(tick, 1000);
  }

  async function finish(){
    if(completed) return;
    completed = true;
    okEl.style.display = "block";
    try{
      const r = await fetch("/api/ad/complete", {
        method: "POST",
        headers: {"Content-Type":"application/json"},
        body: JSON.stringify({ sessionId: SESSION_ID })
      });
      const j = await r.json().catch(()=>({}));
      if(!r.ok || !j.ok){
        okEl.style.display = "none";
        badEl.style.display = "block";
      } else {
        // Telegram WebView usually stays open; user can close it.
        // Optional: auto-close if Telegram WebApp API exists.
        if (window.Telegram && Telegram.WebApp) {
          try { Telegram.WebApp.close(); } catch(e) {}
        }
      }
    }catch(e){
      okEl.style.display = "none";
      badEl.style.display = "block";
    }
  }

  // Start countdown immediately (matches your "overlay countdown" requirement).
  // If you want "countdown only while playing", tell me; we can bind to video play/pause.
  tick();

  // Safety: if user watches full video and it's longer than REQUIRED, also trigger finish on ended (if not already).
  if(vid){
    vid.addEventListener("ended", ()=> finish());
  }
</script>
</body>
</html>
    `);
  } catch (err) {
    console.error(err);
    res.status(500).send("Server error.");
  }
});

/**
 * Marks session completed and credits reward.
 * Called automatically by the ad page when countdown ends.
 */
app.post("/api/ad/complete", async (req, res) => {
  try {
    const { sessionId } = req.body || {};
    if (!sessionId) return res.status(400).json({ ok: false, error: "missing_sessionId" });

    const { data: session, error: sErr } = await supabase
      .from("ad_watch_sessions")
      .select("id,tg_id,ad_id,required_seconds,started_at,paid")
      .eq("id", sessionId)
      .maybeSingle();

    if (sErr || !session) return res.status(404).json({ ok: false, error: "session_not_found" });
    if (session.paid === true) return res.json({ ok: true, already: true });

    const { data: ad, error: aErr } = await supabase
      .from("ads")
      .select("id,seconds,reward,is_active")
      .eq("id", session.ad_id)
      .maybeSingle();

    if (aErr || !ad) return res.status(404).json({ ok: false, error: "ad_not_found" });
    if (ad.is_active !== true) return res.status(400).json({ ok: false, error: "ad_not_active" });

    const requiredSeconds = Math.max(
      10,
      Number(session.required_seconds || ad.seconds || 10)
    );
    const startedAt = new Date(session.started_at);
    const elapsed = (Date.now() - startedAt.getTime()) / 1000;

    if (elapsed + 0.5 < requiredSeconds) {
      // +0.5 tolerance for timer drift
      return res.status(400).json({ ok: false, error: "too_early", elapsed, requiredSeconds });
    }

    const reward = Math.max(0, Number(ad.reward || 0));
    const tgId = String(session.tg_id);

    // 1) Credit user balances (requires users.balance_tl and users.token columns).
    // We use a read-modify-write because some projects don't have RPC increment.
    const { data: user, error: uErr } = await supabase
      .from("users")
      .select("id,tg_id,balance_tl,token")
      .eq("tg_id", tgId)
      .maybeSingle();

    if (uErr || !user) {
      return res.status(400).json({ ok: false, error: "user_not_found" });
    }

    const newTl = Number(user.balance_tl || 0) + reward;
    const newToken = Number(user.token || 0) + reward;

    const { error: upUserErr } = await supabase
      .from("users")
      .update({
        balance_tl: newTl,
        token: newToken,
      })
      .eq("id", user.id);

    if (upUserErr) {
      console.error("update user err:", upUserErr);
      return res.status(500).json({ ok: false, error: "user_update_failed" });
    }

    // 2) Mark session paid + completed
    const { error: upSessErr } = await supabase
      .from("ad_watch_sessions")
      .update({
        paid: true,
        completed_at: new Date().toISOString(),
      })
      .eq("id", session.id);

    if (upSessErr) {
      console.error("update session err:", upSessErr);
      return res.status(500).json({ ok: false, error: "session_update_failed" });
    }

    return res.json({ ok: true, credited: { tl: reward, token: reward } });
  } catch (err) {
    console.error(err);
    return res.status(500).json({ ok: false, error: "server_error" });
  }
});

function escapeHtml(s) {
  return String(s || "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}
function escapeAttr(s) {
  return String(s || "").replace(/"/g, "&quot;");
}

app.listen(PORT, () => {
  console.log("🌐 elmas-web listening on", PORT);
});
